# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: vcpkg CI
on:
  pull_request:
jobs:
  vcpkg-ci:
    uses: ednolan/infra-workflows/.github/workflows/reusable-beman-vcpkg-ci.yml@ednolan/vcpkg-release-workflow
    with:
      port_name: beman-transform-view
